### ISSUE TITLE
CHANGELOG

### ISSUE THREAD

**Issue by scottkidder** [OpenHFT/OpenHFT#20]
Have there been any thoughts on approaching a CHANGELOG convention for all OpenHFT projects? At times it is rather difficult to track all of the distinct issues / features in progress across the projects I am currently working with. I have found http://keepachangelog.com/en/1.0.0/ useful as a starting point on some of my projects . Admittedly, creating and maintaining this across OpenHFT projects will be a large undertaking, but I believe it would greatly benefit users.

**Comment by peter-lawrey** [comment]
I think this is a good practice we need to start doing regularly,
particularly as we grow as a company.

On 10 Aug. 2017 02:59, "Scott Kidder" <notifications@github.com> wrote:

Closed #20 <https://github.com/OpenHFT/OpenHFT/issues/20>.

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/OpenHFT/OpenHFT/issues/20#event-1200155972>, or mute
the thread
